using System.IO;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEngine;
namespace LivingWorld.Game.Bridge.Editor
{
    /// <summary>Stages authoritative content for builds and cleans only marked generated copies.</summary>
    public sealed class StageContent : IPreprocessBuildWithReport, IPostprocessBuildWithReport
    {
        private const string Marker = ".livingworld-generated";
        private const string AssetPath = "Assets/StreamingAssets/Content";
        private static string Target => Path.Combine(Application.streamingAssetsPath, "Content");
        public int callbackOrder => 0;
        public void OnPreprocessBuild(BuildReport report)
        {
            string source = Path.GetFullPath(Path.Combine(Application.dataPath, "../Content"));
            if (Directory.Exists(Target)) throw new BuildFailedException("StreamingAssets/Content already exists. Use Living World/Clean Generated Content for a previously interrupted build; authored content is never overwritten.");
            Directory.CreateDirectory(Target);
            File.WriteAllText(Path.Combine(Target, Marker), "Generated by Living World bridge build staging.");
            try
            {
                foreach (string file in Directory.GetFiles(source, "*.json", SearchOption.AllDirectories))
                { string destination = Path.Combine(Target, file.Substring(source.Length + 1)); Directory.CreateDirectory(Path.GetDirectoryName(destination)); File.Copy(file, destination); }
                AssetDatabase.Refresh();
            }
            catch { Cleanup(); throw; }
        }
        public void OnPostprocessBuild(BuildReport report) => Cleanup();
        [MenuItem("Living World/Clean Generated Content")]
        public static void Cleanup()
        {
            if (!Directory.Exists(Target)) return;
            if (!File.Exists(Path.Combine(Target, Marker))) throw new BuildFailedException("Content is not marked as generated; cleanup refused.");
            if (!AssetDatabase.DeleteAsset(AssetPath))
            {
                Directory.Delete(Target, true);
                string meta = Target + ".meta";
                if (File.Exists(meta)) File.Delete(meta);
                AssetDatabase.Refresh();
            }
        }
    }
}
